### PR TITLE
Baking DropEvents into Performance

### PR DESCRIPTION
**Pull request by mozi-h**
We need to "bake" the Program-DropEvents into the Performance's Events array.
This is to allow manual fretting to overwrite the predetermined fret of a `BassDropEvent`, whilst keeping it future-proof for possible Performance-editors.
This means, all DropEvents occuring atomatically during a Performance recording, are baked into the Program's Event list with the appropriate `BakeType`. This is not the case for other Event types, as only `DropEvent`s can be stored in a Program.
```typescript
export enum EventBakeType {
	AUTO, // Baked Dropevents
	MODIFIED_AUTO, // Baked Dropevents, overridden manually (e.g. frets of a BassDropEvent)
	MANUAL, // Manually done stuff
}
```

### CODE REVIEW

**Comment by Tiedye** [comment]
I'm not seeing why this is necessary.   If anything the `fret` parameter of the `BassDropEvent` should be removed so the note played is deduced by the position of the capo.  If that's the case, unless marble drops can be blocked by the user (no need for this when there is a muting lever) I see no need for this "Baking" of drop events.

**Review by iansedano — APPROVED** [review]
This looks good, nice solution. Another step closer to future proof :)

**Review by ChemiCalChems — APPROVED** [review]

**Comment by mozi-h** [comment]
@Tiedye the reason for the `fret` parameter is to simulate manual pressing of the frets, as it would be quite tedious to do on a computer

**Comment by Tiedye** [comment]
@mozi-h The data representation doesn't have to optimize for minimal events as you wont be writing it manually.  I think the fret parameter should be removed as the same effect can be achieved with a capo and a bass drop event.  As it is it will just complicate player/simulator implementations.

**Comment by mozi-h** [comment]
I can’t quite follow, @Tiedye
The reason for marking the baked `DropEvents` as Auto, Modified (`BassDropEvent` only for now) or Manual, is so (very) future Performance-editors have a way of knowing which is which since they’ll share the same event array.

**Pull request merged**
