### PR TITLE
Initial Schema Definition

### PR DESCRIPTION
**Pull request by adamgoose**
The goal is to simply define the data structure that will be used by many aspects of this "VMMX" concept. It will be used by the online programmer, the midi exporter, persistence API, etc.

### CODE REVIEW

**Comment by mozi-h** [comment]
Example Gist: https://gist.github.com/AndMSWDE97/6a017703e853f20133293a8b608353cc

**Comment by ChemiCalChems** [comment]
Proposal for the storage of note events:

# Problems to be solved (in my opinion)
- Have a consistent way of storing note events, no matter the instrument of the machine it pertains to

If we end up storing notes for the vibraphone and the bass in a different way, we are obviously doing something wrong, since the schema can't support two completely different formats for the same type of object (instruments in this case).

- (Probably good to) Have a format with time as its main dimension, not notes

For a musician, and for us, it's much more useful to iterate over time steps, more than over notes. Iterating over time steps is useful for playback, and also increases readability for the average musician, even if they aren't going to be looking at the internal objects, it's good to think similarly to the end users.

If, on the other hand, we iterate, for example, over vibraphone notes, each "note" storing timing for each time it's played, you'd have to transform it into time-dimensional format for playback anyway, and it's plain undoable for bass strings. You have up to two octaves for bass, that's 24 note arrays per string, times 4 strings.

- Separate instruments from each other

It's important to make each instrument self contained to make the schema usable for programming and readable. Each instrument should contain its own note playback information, as well as other metadata.

# Solution to the problems

Have every instrument keep only its notes. The main proposal I'm making is for the following "note event format", which is very similar to MIDI anyway.

```
NoteEvent = 
	timecode
	noteName
```
Each instrument would have an array of events

```
Instrument = 
	metadata = ...
	noteEvents = NoteEvent[]
	...
```

Advantages, it solves all three issues. Each instrument has notes stored in the same way, just as an array of note events. Note events would be sorted by time, so you just have the "synth" for every instrument go over the array of notes of that instrument in order, and wait until the next note has to be played, instead of having to load all events for all "keys" at the beginning of playback, and having to do sorting. Instruments by definition store their own note events, so we still retain some encapsulation.

**Comment by ollpu** [comment]
Since the machine is heavily based on a static programming wheel, an alternative design to what @ChemiCalChems suggests makes more sense to me:

The static configuration of the machine is stored in one place. This includes programming pins/studs, choice of notes on the vibraphone, etc.

Separate from this there is the performance. This includes pulling muting levers, hitting the crash, controlling dampeners, and bass capos/fretting, or even manually pulling marble drops. The performance itself can contain many loops of the programming wheel. These changes would be stored as some kind of events, similar to the above suggestion.

This means that most constraints of the static programming are implicitly enforced in the data format. There's no way to have two loops of the program wheel with different rhythm on the bass. Initially this would make implementation of these constraints easier I think.

In either format the UI will be challenging to design, that isn't affected so much. How do we balance constraints with convenience? On one hand the app would be a tool to make music with the intrinsic limitations of the machine, but on the other hand it could simplify the process of composing music and working around those limits. We can implement many methods of working with the composition.

**Comment by ollpu** [comment]
Here's a curveball:
What if you want to slow down the programming wheel to a stop, and then play a solo on the vibraphones yourself? If programming wheel time is linked to performance time, there's no notes that can play.

Solving this would require either jumping to a higher tempo and muting all the instruments or jumping to a separate part. In either case, enforcing wheel programming constraints becomes really hard. If the wheel is programmed separately and the time isn't linked, this isn't really an issue.

**Review by mozi-h — APPROVED** [review]

**Pull request merged**
