### PR TITLE
Initial JSON Schema

### PR DESCRIPTION
**Pull request by adamgoose**
The goal is to simply define the data structure that will be used by many aspects of this "VMMX" concept. It will be used by the online programmer, the midi exporter, persistence API, etc.

### CODE REVIEW

**Comment by n0remac** [comment]
So this will be a schema wrapper that will make sure the json file is compatible with MIDI?

**Comment by iansedano** [comment]
Hi

**Comment by ChemiCalChems** [comment]
e

**Comment by adamgoose** [comment]
@n0remac Yes and no. The goal is to simply define the data structure that will be used by many aspects of this "VMMX" concept. It will be used by the online programmer, the midi exporter, persistence API, etc.

**Comment by mozi-h** [comment]
(This PR was just a test)

**Pull request closed without merging**
